USE mangi;

insert into user (email, password, name, is_admin) values
('caroll@gmail.com', '$2a$14$tEd0jOwmOqWKPeBaiW0wQOwwVTYGYwgeng7YsEXdVKbizdSZ92n8m', 'caroll', 1),
('eddy@gmail.com', '$2a$14$tEd0jOwmOqWKPeBaiW0wQOwwVTYGYwgeng7YsEXdVKbizdSZ92n8m', 'eddy', 0),
('ba@gmail.com', '$2a$14$tEd0jOwmOqWKPeBaiW0wQOwwVTYGYwgeng7YsEXdVKbizdSZ92n8m', 'papi', 0),
('hilda@gmail.com', '$2a$14$TmgmLtAL6O5KhsTHiiFRWu3N5gfnZm3EoNm3eGtbuykNfzsokG/6W', 'hilda', 0),
('vincent@gmail.com', '$2a$14$cV7P5ulzHjIhlDOHTHnsGOgHb1FUDjhBAdGg7XXiZ409juzFEMesy', 'vincent', 0),
('shainez@gmail.com', '$2a$14$cV7P5ulzHjIhlDOHTHnsGOgHb1FUDjhBAdGg7XXiZ409juzFEMesy', 'shainez', 0),
('foo@gmail.com', '$2a$14$cV7P5ulzHjIhlDOHTHnsGOgHb1FUDjhBAdGg7XXiZ409juzFEMesy', 'foo', 0),
('bar@gmail.com', '$2a$14$cV7P5ulzHjIhlDOHTHnsGOgHb1FUDjhBAdGg7XXiZ409juzFEMesy', 'bar', 0),
('fizz@gmail.com', '$2a$14$cV7P5ulzHjIhlDOHTHnsGOgHb1FUDjhBAdGg7XXiZ409juzFEMesy', 'fizz', 0),
('valentine@gmail.com', '$2a$14$SVgPmaQWXwbwAfe53wRC0.wiaYCBhyMApQWcFBytU4gHSRfxGHDQW', 'valentine', 0);

insert into home (owner_id, name) values
(1, 'maison'),
(10,'maison'),
(6, 'colloc');

insert into preference (name) values
('vegetarian'),
('vegan'),
('pork'),
('piment'),
('beef'),
('lactose'),
('peanuts'),
('gluten'),
('crustacean'),
('egg'),
('nuts'),
('fructose'),
('seafood'),
('celery'),
('fish'),
('mustard'),
('sesame'),
('soy'),
('sulphites'),
('lupine');

insert into ustensil (name)
values
('microwave'),
('oven'),
('pressure cooker'),
('wok'),
('fryer'),
('mix');

insert into food (name, family, sub_family) values
('piment', 'fruits & légumes', ''),
('beurre', 'laitages', ''),
('beurre de cacahètes', 'épicerie sucré', ''),
('crème de basilic', 'laitages', ''),
('crème fraiche', 'laitages', ''),
('crème fraiche liquide', 'laitages', ''),
('cacahètes', '', ''),
('épices italiennes', 'épicerie', ''),
('épices africaines', 'épicerie', ''),
('épices mexicaine', 'épicerie', ''),
('émincé de boeuf', 'viandes', ''),
('éffiloché de porc', 'viandes', ''),
('fromage rapé à l italienne', 'laitages', 'fromages'),
('fromage frais aux herbes', 'laitages', 'fromages'),
('fromage frais', 'laitages', 'fromages'),
('fromage à tatiner à la truffe', 'laitages', 'fromages'),
('graines de sésame', '', ''),
('huile de sésame', 'épicerie', ''),
('jambon en tranche', 'viandes', ''),
('lait', 'laitages', ''),
('lardons fumés', 'viandes', ''),
('oeuf', 'egg', ''),
('pavé de boeuf', 'viandes', ''),
('pavé de saumon', 'poissons', ''),
('parmesan', 'laitages', 'fromages'),
('sauce asiatique sucré', 'épicerie', ''),
('sauce soja sucré', 'épicerie', ''),
('sauce soja salé', 'épicerie', ''),
('viande haché de boeuf', 'viandes', ''),
('yaourt x', 'laitages', 'yaourt'),
('yaourt y', 'laitages', 'yaourt'),
('yaourt z', 'laitages', 'yaourt'),
('vin blanc', 'boissons', 'alcool'),
('vin rosé', 'boissons', 'alcool'),
('courgette', 'fruits & légumes', ''),
('carotte', 'fruits & légumes', ''),
('haricots verts', 'fruits & légumes', ''),
('poivron', 'fruits & légumes', ''),
('champignon de paris', 'fruits & légumes', ''),
('chocolat', 'épicerie sucré', ''),
('cube de bouillon de légumes', '', ''),
('cube de bouillon de volaille', '', ''),
('chair de tomates', 'fruits & légumes', ''),
('concentré de tomates', '', ''),
('citron', 'fruits & légumes', ''),
('échalote', 'fruits & légumes', ''),
('filet de poulet', 'viandes', ''),
('farfalle', 'pâtes', ''),
('gousse d ail', 'fruits & légumes', ''),
('gingembre frais', 'fruits & légumes', ''),
('gnocchis à poêler', 'pâtes', ''),
('gnocchis', 'pâtes', ''),
('huile d olive', 'épicerie', ''),
('huile de tournesole', 'épicerie', ''),
('haricots rouges', 'fruits & légumes', ''),
('linguines', 'pâtes', ''),
('orzo', 'pâtes', ''),
('oignon', 'fruits & légumes', ''),
('poivre', 'épicerie', ''),
('pomme de terre', 'fruits & légumes', ''),
('patate douce', 'fruits & légumes', ''),
('persil', 'fruits & légumes', ''),
('riz', 'pâtes', ''),
('salade', 'fruits & légumes', ''),
('sel', 'épicerie', ''),
('sauce au poivre', 'épicerie', ''),
('vinaigre balsamique blanc', 'épicerie', ''),
('vinaigre balsamique noir', 'épicerie', ''),
('vinaigre de riz', 'épicerie', ''),
('papier toilette', 'hygiène', 'maison'),
('sopalin', 'hygiène', 'maison'),
('shampoing', 'hygiène', 'personnel'),
('lessive', 'hygiène', 'maison'),
('assouplissant', 'hygiène', 'maison'),
('bicarbonate de soude', 'hygiène', 'maison'),
('savon noir', 'hygiène', 'maison'),
('gel douche', 'hygiène', 'personnel'),
('papier sulfurisé', 'autre', ''),
('papier aluminium', 'autre', ''),
('chewing gum', 'épicerie sucré', ''),
('tampon', 'hygiène', 'personnel'),
('serviette hygiénique', 'hygiène', 'personnel'),
('pack d eau', 'boissons', 'eau'),
('bonbons x', 'épicerie sucré', 'bonbon'),
('bonbons y', 'épicerie sucré', 'bonbon'),
('bonbons z', 'épicerie sucré', 'bonbon'),
('chips', 'épicerie', ''),
('gateaux x', 'épicerie sucré', 'gateau'),
('gateaux y', 'épicerie sucré', 'gateau'),
('gateaux z', 'épicerie sucré', 'gateau'),
('croquettes chat', 'autre', ''),
('croquettes chien', 'autre', ''),
('eponges', 'hygiène', 'maison'),
('vin rouge', 'boissons', 'alcool'),
('vodka', 'boissons', 'alcool'),
('gin', 'boissons', 'alcool'),
('coca cola', 'boissons', 'soda'),
('schweps', 'boissons', 'soda'),
('sucre', 'épicerie sucré', ''),
('Ricotta Galbani', 'laitages', 'fromages'),
('Lait bio demi-écrémé Lactel', 'laitages', 'fromages'),
('Agneau', 'viandes', ''),
('Spaghettis', 'pâtes', ''),
('poudre de 4 épices', 'épicerie', ''),
('pain de mie', 'épicerie', ''),
('épinards', 'fruits & légumes', ''),
('tomates cerises', 'fruits & légumes', ''),
('sel', 'épicerie', ''),
('poivre', 'épicerie', '');

insert into month (name, season) values
('january', 'winter'),
('february', 'winter'),
('march', 'winter'),
('april', 'spring'),
('may', 'spring'),
('june', 'spring'),
('july', 'summer'),
('august', 'summer'),
('september', 'summer'),
('october', 'fall'),
('november', 'fall'),
('december', 'fall');

insert into category (name) values
('vegetarian'),
('vegan'),
('light'),
('fast'),
('calorie-smart'),
('familly'),
('asiat'),
('african'),
('not-chef'),
('piment'),
('christmas'),
('halloween'),
('birthday'),
('appetizer'),
('low-budget');

insert into meal (planned_at, guests, owner_id) values
('2024-11-01 19:00:00', 2, 1),
('2024-11-02 19:00:00', 3, 1),
('2024-11-01 21:00:00', 4, 2),
('2024-11-02 21:00:00', 4, 2);

insert into recipe (name, owner_id, preparation_time, total_time, description, is_public ) values
('Cheasy-easy farfalle aux lardons & courgette', 1, 35, 45, 'a écrire', 1),
('gateau', 1, 15, 40, 'Préchauffez votre four à Th.6 (180°C). Faire fondre le chocolat avec le beurre au micro-ondes 2 mn à 500 W. Dans un saladier, mélangez la farine, les oeufs, le sucre et la levure puis incorporez le chocolat fondu. La pâte doit avoir une consistance onctueuse. Versez-la dans un moule beurré et fariné. Faites cuire dans votre four durant 25 minutes.', 1),
('Orzo & boeuf haché en sauce pomodoro', 1, 45, 65, 'Portez l eau à ébulition dans une casserole avec le cube de bouillon. Ciselez l oignon et l ail. Epluchez la carotte puis rapez-la. Faites cuire l orzo 10-12 min à feu doux et à couvert dans le bouillon en remuant régulièrement. Si l orzo commence à accrocher, ajoutez de l eau. Une fois l orzo cuit, égrenez-le à la fourchette. Faites fondre une noix de beurre dans un wok ou une sauteuse à feu moyen. Faites y revenir l oignon et l ail 1-2min. Ajoutez le concentré de tomate et les épices italiennes (à ajuster). Puis ajoutez le boeuf haché et le vinaigre balsamique noir. Faites revenir 2-3min. Ajoutez la carotte, couvrez et faites cuire 7-10min de plus. Ajoutez le fromage frais aux herbes à la sauteuse ainsi que 2cs d eau par personne et laissez réduire 1min. Ajoutez l orzo. Mélangez. Salé et poivrez selon votre gout. Servez l orzo dans des assiettes creuses et soupoudrez de fromage rapé.', 1),
('Boeuf façon bulgogi sésame & haricots verts', 1, 45, 60, 'a écrire', 1),
('Ropa vieja: porc effiloché à la cubaine', 1, 35, 50, 'a écrire', 1),
('Linguine forestières & fromage à la truffe avec champignons de paris et crème', 1, 30, 45, 'Portez une grande casserole d eau salée à ébullition pour les pâtes. Nettoyez les champignons puis coupez-les en fines tranches. Faites chauffer une noix de beurre dans une grande sauteuse à feu vif. Faites y dorer l échalote et l ail 2min. Ajoutez les champignons, salez et faites sauter le tout 6-8min ou jusqu à ce quils aient relâché toute leur eau et soient dorés. Déglacez les champignons en versant 1cc de vinaigre de riz par personne par-dessus. Poivrez généreusement. Faites cuire les linguine 10-12min dans la casserole. Réservez 1/4 de louche d eau de cuisson par personne puis égoutez les. A feu doux, ajoutez les linguine à la sauteuse ainsi que l eau de cuisson des pâtes, une noix de beurre et le fromage rapé. Remuez bien et laissez chauffer 2-3min ou jusqu à obtenir une consistance crémeuse. Coupez le feu et ajoutez le fromage frais à la truffe. Répartissez la salade dans les assiettes et disposez les pâtes dessus.', 1),
('oeuf au plat', 1, 2, 5, '1: Beurrer une petite poêle. Faire chauffer sur feu moyen. 2: Lorsque le beurre est fondu, casser délicatement les oeufs dans la poêle sans crever le jaune. Saler le blanc mais pas le jaune qui se tacherait de petits points blancs. Pour finir : Laisser cuire 2 ou 3 minutes en étalant légèrement le blanc avec une spatule. Poivrer. Faire glisser les oeufs sur les assiettes à l aide de la spatule.', 1),
('Mafé revisité au poulet & carotte', 1, 30, 50, 'a écrire', 1),
('Tagliata de boeuf à l italienne & sauce basilic avec ses légumes au four', 1, 35, 60, 'Préchauffez votre four à 220° ou 200° en chaleur tournante. Sortez et lavez le boeuf. Lavez et épeluchez les pommes de terre. Coupez les en quartier. Dans un bol, mélangez avec un filet d huile d olive, sel  et poivre. Disposez les pommes de terre sur une plaque recouverte de papier sulfurisé. Enfournez 30-40min. Epéninez le poivron et coupez le en fines lanières (0.5 à 1cm d épaisseur). Retournez les pommes de terre à mi-cuisson. Ajoutez simultanément le poivron sur la même plaque de cuisson assaisonnez le d un filet d huile d olive, des epices italiennes, de sel et de poivre. Enfournez-les encore 15-20min ou jusqu à ce que le poivron soit fondant et doré. Faites une vinaigrette en mélangeant un filet d huile d olive avec du vinaigre balsamique du poivre et du sel dans un bol. Juste avant de servir, ajouter la salade et mélangez bien. Qiand il reste 10min de cuisson aux pommes de terre, faites chauffer un petit filet d huile d olive dans une grande poêle à feu moyen-vif. Epongez la viande puis salez et poivrez la. Quand l huile est bien chaude, faites cuire la viande 2-3min de chaque côté ou jusqu à ce qu elle soit dorée. Réservez la dans une assiette recouverte d aluminium jusqu au service. Disposez la salade sur les assiettes. Coupez la viande en fines tranches dans le sens inverse de leur fibres. Disposez-les sur la salade. Ajoutez la moitié de la crème de basilic par-dessus. Servez les pommes de terre et le poivron rotis à côté avec de la creme de basilic.', 1 ),
('Pasta aux boulettes d agneau et Ricotta', 1, 20, 45, "Coupez l'agneau en morceaux grossiers, et placez-les ensuite dans le bol d’un hachoir avec la c. à café de 4 épices. Faites fonctionner le hachoir par a-coup pour obtenir un hachis fin. Mettez le pain de mie à tremper dans le lait. Mélangez ensemble le hachis d'agneau, le pain de mie, l'œuf, la ricotta et le jus de citron. Formez ensuite 12 boulettes de 4 cm de diamètre environ, en les roulant dans vos mains légèrement farinées. Réservez. Epluchez et coupez l'oignon finement. Rincez les tomates. Faites bouillir le bouillon de légumes et l'eau. Plongez-y ensuite les spaghettis, les épinards, l'oignon, les tomates, le persil ciselé et les boulettes d'agneau. Laissez cuire à feu moyen pendant 10-12 minutes, jusqu'à ce que le bouillon soit évaporé et les pâtes cuites. Egouttez le tout. Servez bien chaud à l'assiette ce One Pot Pasta à l’agneau et ricotta.", 1);

insert into user_home (home_id, user_id)
values
(1, 1),
(1, 2),
(1, 3),
(2, 10),
(3, 6),
(3, 7),
(3, 8),
(3, 9);

insert into user_preference (user_id, preference_id, exist) values
(1, 1, 1),
(1, 2, 1),
(1, 3, 1),
(1, 4, 1),
(1, 5, 1),
(1, 6, 1),
(1, 7, 1),
(1, 8, 1),
(1, 9, 1),
(1, 10, 1),
(1, 11, 1),
(1, 12, 1),
(1, 13, 1),
(1, 14, 1),
(1, 15, 1),
(1, 16, 1),
(1, 17, 1),
(1, 18, 1),
(1, 19, 1),
(1, 20, 1),
(2, 1, 1),
(2, 2, 1),
(2, 3, 1),
(2, 4, 1),
(2, 5, 1),
(2, 6, 1),
(2, 7, 1),
(2, 8, 1),
(2, 9, 1),
(2, 10, 1),
(2, 11, 1),
(2, 12, 1),
(2, 13, 1),
(2, 14, 1),
(2, 15, 1),
(2, 16, 1),
(2, 17, 1),
(2, 18, 1),
(2, 19, 1),
(2, 20, 1),
(3, 1, 1),
(3, 2, 1),
(3, 3, 1),
(3, 4, 1),
(3, 5, 1),
(3, 6, 1),
(3, 7, 1),
(3, 8, 1),
(3, 9, 1),
(3, 10, 1),
(3, 11, 1),
(3, 12, 1),
(3, 13, 1),
(3, 14, 1),
(3, 15, 1),
(3, 16, 1),
(3, 17, 1),
(3, 18, 1),
(3, 19, 1),
(3, 20, 1),
(4, 1, 1),
(4, 2, 1),
(4, 3, 0),
(4, 4, 1),
(4, 5, 1),
(4, 6, 1),
(4, 7, 1),
(4, 8, 1),
(4, 9, 1),
(4, 10, 1),
(4, 11, 1),
(4, 12, 1),
(4, 13, 1),
(4, 14, 1),
(4, 15, 1),
(4, 16, 1),
(4, 17, 1),
(4, 18, 1),
(4, 19, 0),
(4, 20, 1),
(5, 1, 1),
(5, 2, 1),
(5, 3, 1),
(5, 4, 1),
(5, 5, 1),
(5, 6, 1),
(5, 7, 1),
(5, 8, 1),
(5, 9, 1),
(5, 10, 1),
(5, 11, 1),
(5, 12, 1),
(5, 13, 1),
(5, 14, 1),
(5, 15, 1),
(5, 16, 1),
(5, 17, 1),
(5, 18, 1),
(5, 19, 1),
(5, 20, 1),
(6, 1, 1),
(6, 2, 1),
(6, 3, 0),
(6, 4, 1),
(6, 5, 1),
(6, 6, 1),
(6, 7, 1),
(6, 8, 1),
(6, 9, 1),
(6, 10, 1),
(6, 11, 1),
(6, 12, 1),
(6, 13, 1),
(6, 14, 1),
(6, 15, 1),
(6, 16, 1),
(6, 17, 1),
(6, 18, 1),
(6, 19, 1),
(6, 20, 1),
(7, 1, 1),
(7, 2, 1),
(7, 3, 1),
(7, 4, 1),
(7, 5, 1),
(7, 6, 1),
(7, 7, 1),
(7, 8, 1),
(7, 9, 1),
(7, 10, 1),
(7, 11, 1),
(7, 12, 1),
(7, 13, 1),
(7, 14, 1),
(7, 15, 1),
(7, 16, 1),
(7, 17, 1),
(7, 18, 1),
(7, 19, 1),
(7, 20, 1),
(8, 1, 1),
(8, 2, 1),
(8, 3, 1),
(8, 4, 1),
(8, 5, 1),
(8, 6, 1),
(8, 7, 1),
(8, 8, 1),
(8, 9, 1),
(8, 10, 1),
(8, 11, 1),
(8, 12, 1),
(8, 13, 1),
(8, 14, 1),
(8, 15, 1),
(8, 16, 1),
(8, 17, 1),
(8, 18, 1),
(8, 19, 1),
(8, 20, 1),
(9, 1, 1),
(9, 2, 1),
(9, 3, 1),
(9, 4, 1),
(9, 5, 1),
(9, 6, 1),
(9, 7, 1),
(9, 8, 1),
(9, 9, 1),
(9, 10, 1),
(9, 11, 1),
(9, 12, 1),
(9, 13, 1),
(9, 14, 1),
(9, 15, 1),
(9, 16, 1),
(9, 17, 1),
(9, 18, 1),
(9, 19, 1),
(9, 20, 1),
(10, 1, 1),
(10, 2, 1),
(10, 3, 1),
(10, 4, 0),
(10, 5, 1),
(10, 6, 1),
(10, 7, 1),
(10, 8, 1),
(10, 9, 1),
(10, 10, 1),
(10, 11, 1),
(10, 12, 1),
(10, 13, 1),
(10, 14, 1),
(10, 15, 1),
(10, 16, 1),
(10, 17, 1),
(10, 18, 1),
(10, 19, 1),
(10, 20, 1);

insert into user_ustensil (user_id, ustensil_id, exist)
values
(1, 1, 1),
(1, 2, 1),
(1, 3, 1),
(1, 4, 1),
(1, 5, 1),
(1, 6, 0),
(2, 1, 1),
(2, 2, 1),
(2, 3, 1),
(2, 4, 1),
(2, 5, 1),
(2, 6, 1),
(3, 1, 1),
(3, 2, 1),
(3, 3, 1),
(3, 4, 1),
(3, 5, 1),
(3, 6, 1),
(4, 1, 1),
(4, 2, 1),
(4, 3, 1),
(4, 4, 1),
(4, 5, 1),
(4, 6, 1),
(5, 1, 1),
(5, 2, 1),
(5, 3, 1),
(5, 4, 1),
(5, 5, 1),
(5, 6, 1),
(6, 1, 1),
(6, 2, 1),
(6, 3, 1),
(6, 4, 1),
(6, 5, 1),
(6, 6, 1),
(7, 1, 1),
(7, 2, 1),
(7, 3, 1),
(7, 4, 1),
(7, 5, 1),
(7, 6, 1),
(8, 1, 1),
(8, 2, 1),
(8, 3, 1),
(8, 4, 1),
(8, 5, 1),
(8, 6, 1),
(9, 1, 1),
(9, 2, 1),
(9, 3, 1),
(9, 4, 1),
(9, 5, 1),
(9, 6, 1),
(10, 1, 1),
(10, 2, 1),
(10, 3, 0),
(10, 4, 0),
(10, 5, 1),
(10, 6, 1);

insert into food_preference (food_id, preference_id)
values
(1, 4),
(2, 6),
(3, 7),
(4, 6),
(5, 6),
(6, 6),
(7, 7),
(8, 4),
(9, 4),
(10, 4),
(11, 5),
(12, 3),
(13, 6),
(14, 6),
(15, 6),
(16, 6),
(17, 17),
(18, 17),
(19, 3),
(20, 6),
(21, 3),
(22, 10),
(23, 5),
(24, 15),
(25, 6),
(26, 18),
(27, 18),
(28, 18),
(29, 5),
(30, 6),
(31, 6),
(32, 6),
(33, 19),
(34, 19);

insert into food_month (food_id, month_id)
values
(35, 6),
(35, 7),
(35, 8),
(35, 9),
(36, 6),
(36, 7),
(36, 8),
(36, 9),
(36, 10),
(36, 11),
(37, 7),
(37, 8),
(37, 9),
(38, 6),
(38, 7),
(38, 8),
(38, 9),
(38, 10);

insert into ustensil_recipe (ustensil_id, recipe_id) values
(1, 4),
(2, 2),
(8, 4);

insert into recipe_category (recipe_id, category_id) values
(1, 7),
(1, 9),
(2, 9),
(2, 13),
(3, 6),
(4, 3),
(4, 9),
(5, 6),
(5, 7),
(5, 8),
(6, 1),
(7, 4),
(7, 8),
(10, 4),
(10, 9),
(10, 6),
(10, 15),
(7, 15);

insert into meal_recipe (meal_id, recipe_id) values 
(1, 7),
(2, 3),
(3, 9),
(4, 9);

insert into recipe_food (recipe_id, food_id, quantity, unit) values
(7, 2, 1, 'cc'),
(7, 22, 1, 'u'),
(3, 5, 130, 'g'),
(3, 58, 0.4, 'u'),
(3, 49, 0.3, 'u'),
(3, 36, 0.5, 'u'),
(3, 44, 5, 'g'),
(3, 8, 1, 'cc'),
(3, 29, 50, 'g'),
(3, 14, 2, 'cc'),
(3, 13, 2, 'cc'),
(3, 41, 1, 'u'),
(3, 2, 0.5, 'cs'),
(3, 68, 1, 'cc'),
(1, 48, 100, 'g'),
(1, 21, 100, 'g'),
(1, 49, 0.3, 'u'),
(1, 62, 5, 'g'),
(1, 35, 0.5, 'u'),
(1, 45, 0.25, 'u'),
(1, 13, 10, 'g'),
(1, 14, 1.5, 'cs'),
(1, 53, 0.5, 'cs'),
(5, 63, 80, 'g'),
(5, 58, 0.5, 'u'),
(5, 38, 0.5, 'u'),
(5, 55, 40, 'g'),
(5, 62, 1, 'cc'),
(5, 45, 0.25, 'u'),
(5, 12, 30, 'g'),
(5, 10, 1, 'cc'),
(5, 43, 10, 'g'),
(5, 53, 0.5, 'cs'),
(5, 41, 1, 'u'),
(9, 23, 1, 'u'),
(9, 60, 350, 'g'),
(9, 38, 0.5, 'u'),
(9, 8, 1, 'cc'),
(9, 4, 1.5, 'cs'),
(9, 53, 2, 'cs'),
(9, 68, 1, 'cc'),
(2, 2, 150, 'g'),
(4, 29, 150, 'g'),
(6, 56, 150, 'g'),
(2, 40, 150, 'g'),
(10, 100, 20, 'g'),
(10, 101, 0.5, 'cs'),
(10, 102, 75, 'g'),
(10, 103, 90, 'g'),
(10, 104, 0.5, 'cc'),
(10, 22, 0.5, 'u'),
(10, 45, 1, 'u'),
(10, 41, 50, 'cl'),
(10, 106, 50, 'g'),
(10, 58, 0.5, 'u'),
(10, 107, 2, 'u'),
(10, 62, 3, 'g');